<div class="container-fluid py-4 px-3 px-lg-4">
      <div class="alert alert-warning d-none" id="clientScopeNotice"></div>
      <div class="glass p-3 mb-3"><div class="d-flex flex-column flex-lg-row gap-2 align-items-lg-center justify-content-between"><div><div class="section-title">Bonus Control Defaults</div><div class="small text-muted-3">Controlled from Control Page. Preview values remain editable.</div></div><div class="d-flex flex-wrap gap-2"><span class="pill"><i class="bi bi-toggle-on"></i> <span id="controlBadge">-</span></span><span class="pill"><i class="bi bi-calculator"></i> <span id="controlFormula">-</span></span></div></div></div>
      <form id="bonusForm" class="glass p-3 mb-3"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label fw-semibold">Month</label><select id="monthInput" class="form-select"><option value="1">January</option><option value="2">February</option><option value="3">March</option><option value="4">April</option><option value="5">May</option><option value="6">June</option><option value="7">July</option><option value="8">August</option><option value="9">September</option><option value="10">October</option><option value="11">November</option><option value="12">December</option></select></div><div class="col-md-4"><label class="form-label fw-semibold">Year</label><input type="number" id="yearInput" class="form-control" min="2000" step="1"></div><div class="col-md-4"><label class="form-label fw-semibold">Action</label><button class="btn btn-primary w-100" type="submit"><i class="bi bi-magic"></i> Generate</button></div></div></form>
      <div class="glass p-3 mb-3 d-none" id="previewWrap"><div class="section-head mb-2"><div><h6 class="fw-bold mb-0">Preview Table</h6><div class="text-muted-3" id="previewTitle">Generated bonus preview</div></div><button id="btnSavePreview" class="btn btn-sm btn-primary" type="button"><i class="bi bi-save"></i> Save Preview</button></div><div class="table-responsive"><table class="table table-hover align-middle mb-0" data-no-datetime="true"><thead><tr><th>Sr. No</th><th>Employee</th><th>Minimum Wages</th><th>Months</th><th>Bonus %</th><th>Bonus</th></tr></thead><tbody id="previewTable"></tbody></table></div></div>
      <div class="glass p-3"><div class="section-head mb-2"><div><h6 class="fw-bold mb-0">Saved Bonus Sheets</h6><div class="text-muted-3">Stored month/year bonus records</div></div><button id="btnClearAll" class="btn btn-sm btn-outline-danger" type="button"><i class="bi bi-trash"></i> Clear History</button></div><div class="table-responsive"><table class="table table-hover align-middle mb-0" data-no-datetime="true"><thead><tr><th>Sr. No</th><th>Period</th><th>Rows</th><th>Total Bonus</th><th>Generated On</th><th class="text-end">Action</th></tr></thead><tbody id="bonusTable"></tbody></table></div></div>
    </div>

@push('modals')
</div>
</div><button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button></div>
@endpush
